announcements/urls.py
from django.conf.urls import url

from .views import *

app_name = 'announcements'

urlpatterns = [
    url(r'^$', announcement_list, name='list'),
    url(r'^create$', announcement_create, name='create'),
    url(r'^(?P<pk>\d+)$', announcement_detail, name='detail'),
    url(r'^(?P<pk>\d+)/update$', announcement_update, name='update'),
    url(r'^(?P<pk>\d+)/delete$', announcement_delete, name='delete'),
    url(r'^ytdata/(?P<video_id>[a-zA-Z0-9_-]{11})$', ytdata, name='ytdata'),
    url(r'^generator$', generator, name='generator'),
]

api/urls.py
from django.conf.urls import url

from accounts import api_views as accounts_api
from categories import api_views as categories_api
from announcements import api_views as announcements_api
from events import api_views as events_api
from polls import api_views as polls_api
from push_notifications.api.rest_framework import APNSDeviceAuthorizedViewSet
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter
from django.conf.urls import include
app_name = 'api'

router = DefaultRouter()
router.register(r'device/apns', APNSDeviceAuthorizedViewSet)

urlpatterns = [

    url(r'^users/$', accounts_api.UserViewSet.as_view({'get':'list', 'post':'create'}), name='users'),
    url(r'^users/(?P<pk>\d+)$', accounts_api.UserViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='user'),

    url(r'^user_profiles/$', accounts_api.UserProfileViewSet.as_view({'get':'list', 'post':'create'}), name='user_profiles'),
    url(r'^user_profiles/(?P<pk>\d+)$', accounts_api.UserProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='user_profile'),

    url(r'^student_profiles/$', accounts_api.StudentProfileViewSet.as_view({'get':'list', 'post':'create'}), name='student_profiles'),
    url(r'^student_profiles/(?P<pk>\d+)$', accounts_api.StudentProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='student_profile'),

    url(r'^teacher_profiles/$', accounts_api.TeacherProfileViewSet.as_view({'get':'list', 'post':'create'}), name='teacher_profiles'),
    url(r'^teacher_profiles(?P<pk>\d+)/$', accounts_api.TeacherProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='teacher_profile'),

    url(r'^categories/$', categories_api.CategoryViewSet.as_view({'get':'list', 'post':'create'}), name='categories'),
    url(r'^categories/(?P<pk>\d+)$', categories_api.CategoryViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='category'),

    url(r'^announcements/$', announcements_api.AnnouncementViewSet.as_view({'get':'list', 'post':'create'}), name='announcements'),
    url(r'^announcements/(?P<pk>\d+)$', announcements_api.AnnouncementViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='announcement'),

    url(r'^image_files/$', announcements_api.ImageFileViewSet.as_view({'get':'list', 'post':'create'}), name='image_files'),
    url(r'^image_files/(?P<pk>\d+)$', announcements_api.ImageFileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='image_file'),

    url(r'^image_links/$', announcements_api.ImageLinkViewSet.as_view({'get':'list', 'post':'create'}), name='image_links'),
    url(r'^image_links/(?P<pk>\d+)$', announcements_api.ImageLinkViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='image_link'),

    url(r'^youtube_videos/$', announcements_api.YouTubeVideoViewSet.as_view({'get':'list', 'post':'create'}), name='youtube_videos'),
    url(r'^youtube_videos/(?P<pk>\d+)$', announcements_api.YouTubeVideoViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='youtube_video'),

    url(r'^events/$', events_api.EventViewSet.as_view({'get':'list', 'post':'create'}), name='events'),
    url(r'^events(?P<pk>\d+)/$', events_api.EventViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='event'),

    url(r'^polls/$', polls_api.PollViewSet.as_view({'get':'list', 'post':'create'}), name='polls'),
    url(r'^polls/(?P<pk>\d+)$', polls_api.PollViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='poll'),

    url(r'^choices/$', polls_api.ChoiceViewSet.as_view({'get':'list', 'post':'create'}), name='choices'),
    url(r'^choices/(?P<pk>\d+)$', polls_api.ChoiceViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='choice'),

    url(r'^votes/$', polls_api.VoteViewSet.as_view({'get':'list', 'post':'create'}), name='votes'),
    url(r'^votes/(?P<pk>\d+)$', polls_api.VoteViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='vote'),

    # url(r'^', include(router.urls)),
    # url(r'^subjects/$', views_api.SubjectViewSet.as_view({'get':'list', 'post':'create'}), name='subjects'),
    # url(r'^subjects/(?P<pk>\d+)$', views_api.SubjectViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='subject'),
    #
    # url(r'^classes/$', views_api.ClassViewSet.as_view({'get':'list', 'post':'create'}), name='classes'),
    # url(r'^classes/(?P<pk>\d+)$', views_api.ClassViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='class'),
    #
    # url(r'^schedules/$', views_api.ScheduleViewSet.as_view({'get':'list', 'post':'create'}), name='schedules'),
    # url(r'^schedules/(?P<pk>\d+)$', views_api.ScheduleViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='schedule'),

]

announcements/forms.py
from django import forms

from .models import *
from categories.models import *
from base.forms import category_form_field

class AnnouncementForm(forms.ModelForm):
    category = category_form_field

    class Meta:
        model = Announcement
        fields = ('title', 'category', 'content')
        widgets = {
            'title': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Add a short, clear title', 'required':'required', 'autofocus':'autofocus'}),
            'content': forms.Textarea(attrs={'class':'form-control', 'placeholder':'Announcement body goes here', 'rows':'4', 'required':'required'}),
        }

announcements/views.py
from .models import *
from .forms import *
from categories.models import *
from push_notifications.models import APNSDevice

import json
import requests

from django.http import HttpResponse, JsonResponse, Http404
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

@login_required
def announcement_list(request):
    hidden = request.user.profile.categories_hidden_announcements.values_list('pk', flat=True)
    categories_hidden_announcements = Category.objects.filter(pk__in=hidden)
    categories_shown = Category.objects.exclude(pk__in=hidden)
    return render(request, 'announcements/announcement_list.html', {'categories_shown': categories_shown, 'categories_hidden_announcements': categories_hidden_announcements})

@login_required
def announcement_detail(request, pk):
    announcement = Announcement.objects.get(pk=pk)
    return render(request, 'announcements/announcement_detail.html', {'announcement': announcement})

@staff_member_required()
def announcement_create(request):
    form = AnnouncementForm(request.POST or None)
    if form.is_valid():
        a = form.save(commit=False)
        a.author = request.user.profile
        a.save()

        image_files = request.FILES.getlist('image-files')
        image_links = request.POST.getlist('image-links')
        youtube_videos = request.POST.getlist('youtube-videos')

        for image_file in image_files:
            f = ImageFile(image_file=image_file, announcement=a)
            f.save()
        for image_link in image_links:
            link = ImageLink(image_link=image_link, announcement=a)
            link.save()
        for youtube_video in youtube_videos:
            video = YouTubeVideo(youtube_video=youtube_video, announcement=a)
            video.save()

        # TODO: Push Notifications
        devices = APNSDevice.objects.all()
        devices.send_message("New Announcement!");

        return redirect('announcements:list')
    return render(request, 'announcements/announcement_create.html', {'form': form})

@staff_member_required()
def announcement_update(request, pk):
    #TODO: restrict access to either the original author or a superuser admin
    announcement = Announcement.objects.get(pk=pk)
    form = AnnouncementForm(request.POST or None, instance=announcement)
    if form.is_valid():
        a = form.save()

        image_files = request.FILES.getlist('image-files')
        image_links = request.POST.getlist('image-links')
        youtube_videos = request.POST.getlist('youtube-videos')

        for image_file in image_files:
            i = ImageFile(image_file=image_file, announcement=a)
            i.save()
        for image_link in image_links:
            i = ImageLink(image_link=image_link, announcement=a)
            i.save()
        for youtube_video in youtube_videos:
            v = YouTubeVideo(youtube_video=youtube_video, announcement=a)
            v.save()

        # TODO: Define model's get_absolute_url() and redirect() to the model instance redirect(model_instance)
        return redirect(announcement)
    return render(request, 'announcements/announcement_update.html', {'form': form, 'announcement': announcement})

@staff_member_required()
def announcement_delete(request, pk):
    #TODO: restrict access to either the original author or a superuser admin
    announcement = Announcement.objects.get(pk=pk)
    announcement.delete()
    return redirect('announcements:list')

@staff_member_required()
def pin_announcement(request, pk):
    a = Announcement.objects.get(pk=pk)
    a.pin()
    return redirect('announcements:list')

@staff_member_required()
def unpin_announcement(request, pk):
    a = Announcement.objects.get(pk=pk)
    a.unpin()
    return redirect('announcements:list')

@staff_member_required
def ytdata(request, video_id):
    r = requests.get('https://www.youtube.com/oembed?url=http://www.youtube.com/watch?v=' + video_id + '&format=json')
    if r.status_code == 200:
        json_data = r.text
        data = json.loads(json_data)
        return JsonResponse(data)
    else:
        raise Http404()

@staff_member_required
def generator(request):
    if request.method == 'POST':
        count = int(request.GET.get('count'))
        generated_count = Announcement.generate_random_objects(count)
        if (generated_count == count):
            return HttpResponse('Success: %d announcements were generated' % generated_count)
        else:
            return HttpResponse('Error: %d announcements were generated' % generated_count)

announcements/templates/announcements/announcement_create.html
{% extends "announcements/announcement_form.html" %}

{% load static from staticfiles %}

{% block title %}Create Announcement{% endblock %}

{% block sidebar_announcement_create %}selected{% endblock %}

{% block form_id %}announcement-create-form{% endblock %}{% block form_url %}{% url 'announcements:create' %}{% endblock %}

{% block image_file_preview %}
  <!-- Image Preview -->
  <div class="image-list form"><span id="image-files-preview"></span></div>
{% endblock %}

{% block image_link_preview %}
  <!-- Image Preview -->
  <div class="image-list form"><span id="image-links-preview"></span></div>
{% endblock %}

{% block youtube_video_preview %}
  <!-- YouTube Video Preview -->
  <div id="youtube-videos-preview"></div>
{% endblock %}

{% block submit_button_id %}submit-announcement-create-form{% endblock %}

announcements/templates/announcements/announcement_detail.html
{% extends 'base/base.html' %}

{% load static from staticfiles %}

{% block title %}Announcement Detail{% endblock %}

{% block masthead_announcements %}selected{% endblock %}

{% block sidebar_announcements %}selected{% endblock %}

{% block sidebar_extra %}
  <hr class="sidebar-divider">
  <ul id="sidebar-admin-announcement">
    <a href="#" class="sidebar-header">Announcement</a>
    <li><a href="{% url 'announcements:update' announcement.pk %}">
      <span class="icon-container"><span class="glyphicon glyphicon-pencil"></span></span>
      <span class="display-name">Make Changes</span>
    </a></li>
    <li><a href="#">
      <span class="icon-container"><span class="glyphicon glyphicon-remove"></span></span>
      <span class="display-name">Delete</span>
    </a></li>
  </ul>
{% endblock %}

{% block content %}
  <div id="announcement-{{ announcement.pk }}" class="announcement-wrapper container-white" style="border-left: 5px solid {{ announcement.category.color|default:'#222222' }}" data-category-pk="{{ announcement.category.pk }}">
    <div class="signature">
      <!-- Announcement Title -->
      <span><a style="font-size: 16px; font-weight: 500" href="{% url 'announcements:list' %}"><div>{{ announcement.title }}</div></a></span> &bull;
      <!-- Announcement Signature -->
      <span>{{ announcement.category|default_if_none:'General' }}</span>
      <span class="date-created" style="float:right; margin:3px 0px;">{{ announcement.date_created|date:'M j' }}</span>
        <!-- <span class="time-created">{% templatetag openvariable %} timeCreated {% templatetag closevariable %}</span> -->
    </div>
    <!-- Announcement Content -->
    <div class="content">{{ announcement.content }}</div>
    <!-- Announcement Media -->
    <div class="announcement-media">
      <!-- Announcement Images -->
      <div class="image-list">
        {% for image in announcement.image_files.all %}<div class="image"><a href="{{ image.image_file.url }}" target="_blank" title="Click to open in new tab"><img src="{{ image.image_file_thumbnail.url }}"></a></div>{% endfor %}{% for image in announcement.image_links.all %}<div class="image"><a href="{{ image.image_link }}" target="_blank" title="Click to open in new tab"><img src="{{ image.image_file_thumbnail.url }}"></a></div>{% endfor %}
      </div>
      <!-- Announcement Videos -->
      <div class="video-list">
        {% for video in announcement.youtube_videos.all %}
          <div class="embed-responsive embed-responsive-16by9 video"><iframe class="embed-responsive-item" src="https://www.youtube.com/embed/{{ video.youtube_video }}" allowfullscreen></iframe></div>
        {% endfor %}
      </div>
    </div>
  </div>
{% endblock %}

announcements/templates/announcements/announcement_form.html
{% extends 'base/base.html' %}

{% load static from staticfiles %}

{% block masthead_announcements %}selected{% endblock %}

{% block content %}
  <div class="container-white">
    <form id="{% block form_id %}{% endblock %}" action="{% block form_url %}{% endblock %}" enctype="multipart/form-data" method="post" >{% csrf_token %}
      <!-- Announcement Title -->
      <div class="row">
        <div class="col-xs-2"><div class="form-label">Title</div></div>
        <div class="col-xs-10"><div class="validate-required">{{ form.title }}</div></div>
      </div><br>
      <!-- Announcement Content -->
      <div class="row">
        <div class="col-xs-2"><div class="form-label">Content</div></div>
        <div class="col-xs-10"><div class="validate-required">{{ form.content }}</div></div>
      </div><br>
      <!-- Announcement Category -->
      <div class="row">
        <div class="col-xs-2"><div class="form-label">Tag</div></div>
        <div class="col-xs-10">{{ form.category }}</div>
      </div><br>
      <!-- Announcement Media Tabs -->
      <div class="row">
        <div class="col-xs-2"><div class="form-label">Media</div></div>
        <div class="col-xs-10">
          <ul class="nav nav-tabs" role="tablist">
            <li class="active"><a href="#image-files" data-toggle="tab">Image Files</a></li>
            <li><a href="#image-links" data-toggle="tab">Image Links</a></li>
            <li><a href="#youtube-videos" data-toggle="tab">YouTube Videos</a></li>
          </ul>
        </div>
      </div><br>
      <!-- Announcement Media Tab Panes -->
      <div class="row">
        <div class="col-xs-2">

        </div>
        <div class="col-xs-10">
          <div class="tab-content">
            <!-- Image Files -->
            <div id="image-files" class="tab-pane fade in active">
              <!-- Temporary Alert to User-->
              <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                <strong>Note:</strong> Image preview opens a new tab <span class="glyphicon glyphicon-new-window"></span>
              </div>
              <!-- Hidden Multi-file Input -->
              <input id="image-files-add" class="hidden" type="file" name="image-files" accept="image/*" multiple>
              <div class="text-center">
                <!-- Add Button-->
                <label class="btn btn-custom" for="image-files-add">
                  Choose Images
                  <span class="badge hidden">
                    <span class="count"></span>
                    <span class="glyphicon glyphicon-refresh"></span>
                    <span class="glyphicon glyphicon-ok"></span>
                  </span>
                </label>
                <!-- Clear Button-->
                <div class="inline-block">
                  <button type="button" id="image-files-clear" class="close hidden" title="Clear" data-toggle="tooltip" data-placement="top"><span>&times;</span></button>
                </div>
              </div><br>
              <!-- Image Labels (filename/size) -->
              <div id="image-files-filenames" class="text-center"></div>
              {% block image_file_preview %}{% endblock %}
            </div>
            <!-- Image Links -->
            <div id="image-links" class="tab-pane fade">
              <!-- Temporary Alert to User-->
              <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                <strong>Note:</strong> Image preview opens a new tab <span class="glyphicon glyphicon-new-window"></span>
              </div>
              <!-- Image URL Input -->
              <div class="has-feedback">
                <input id="image-links-add" type="url" class="form-control" name="image-links" placeholder="Paste link to image here">
                <span class="glyphicon glyphicon-remove form-control-feedback hidden"></span>
              </div><br>
              <!-- Hidden Image Tester -->
              <img id="image-tester" src="#" data-status="0" hidden>
              {% block image_link_preview %}{% endblock %}
            </div>
            <!-- YouTube Videos -->
            <div id="youtube-videos" class="tab-pane fade">
              <!-- Temporary Alert to User-->
              <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span>&times;</span></button>
                <strong>Note:</strong> Video preview opens a new tab <span class="glyphicon glyphicon-new-window"></span>
              </div>
              <!-- YouTube Video URL Input -->
              <div class="has-feedback">
                <input id="youtube-videos-add" type="url" class="form-control" name="youtube-videos" placeholder="Paste link to YouTube video here">
                <span class="glyphicon glyphicon-remove form-control-feedback hidden"></span>
              </div><br>
              {% block youtube_video_preview %}{% endblock %}
            </div>
          </div><hr>
        </div>
      </div>
      <!-- Buttons -->
      <div class="text-right">
        <a class="btn btn-sm btn-default" href="{% block cancel_button_target_url %}{% url 'announcements:list' %}{% endblock %}">Cancel</a>
        <button id="{% block submit_button_id %}{% endblock %}" class="btn btn-sm btn-custom" type="button">{% block submit_button_text %}Publish{% endblock %}</button>
      </div>
    </form>
  </div>
{% endblock %}

{% block templates %}
  <!-- Image File Template -->
  <template id="image-file-template">
    <div class="image">
      <a href="{% templatetag openvariable %} imageURL {% templatetag closevariable %}" target="_blank" title="Click to open in new tab">
        <div class="image-thumbnail" style="background-image: url('{% templatetag openvariable %} imageURL {% templatetag closevariable %}')"></div>
      </a>
    </div>
  </template>
  <!-- Image Link Template -->
  <template id="image-link-template">
    <div class="image">
      <a href="{% templatetag openvariable %} imageURL {% templatetag closevariable %}" target="_blank" title="Click to open in new tab">
        <div class="image-thumbnail" style="background-image: url('{% templatetag openvariable %} imageURL {% templatetag closevariable %}')"></div>
      </a>
    </div><input name="image-links" value="{% templatetag openvariable %} imageURL {% templatetag closevariable %}" required hidden>
  </template>
  <!-- YouTube Video Template -->
  <template id="youtube-video-template">
    <div class="row youtube-video-preview-wrapper">
      <div class="col-xs-4 youtube-video-thumbnail">
        <!-- Thumbnail -->
        <a href="https://www.youtube.com/watch?v={% templatetag openvariable %} videoID {% templatetag closevariable %}" target="_blank"><img src="{% templatetag openvariable %} thumbnailURL {% templatetag closevariable %}"></a>
      </div>
      <div class="col-xs-8 youtube-video-details" style="font-size:12px">
        <!-- Title -->
        <div class="title">
          <a href="https://www.youtube.com/watch?v={% templatetag openvariable %} videoID {% templatetag closevariable %}" target="_blank"><div>{% templatetag openvariable %} videoTitle {% templatetag closevariable %}</div></a>
        </div>
        <!-- Author (Channel Name) -->
        <div class="author">
          <a href="{% templatetag openvariable %} videoAuthorURL {% templatetag closevariable %}" target="_blank">{% templatetag openvariable %} videoAuthor {% templatetag closevariable %}</a>
        </div>
      </div>
      <input name="youtube-videos" value="{% templatetag openvariable %} videoID {% templatetag closevariable %}" maxlength="11" required hidden>
    </div>
  </template>
{% endblock %}

{% block script %}<script src="{% static 'announcements/js/announcement_form.js' %}"></script>{% endblock %}

announcements/templates/announcements/announcement_update.html
{% extends "announcements/announcement_form.html" %}

{% load static from staticfiles %}

{% block title %}Update Announcement{% endblock %}

{% block form_id %}announcement-update-form{% endblock %}{% block form_url %}{% url 'announcements:update' announcement.pk %}{% endblock %}

{% block sidebar_extra %}
  <hr class="sidebar-divider">
  <ul id="sidebar-admin-announcement">
    <a href="#" class="sidebar-header">Announcement Tools</a>
    <li><a href="{% url 'announcements:update' announcement.pk %}" class="selected">
      <span class="icon-container"><span class="glyphicon glyphicon-pencil"></span></span>
      <span class="display-name">Make Changes</span>
    </a></li>
    <li><a href="#">
      <span class="icon-container"><span class="glyphicon glyphicon-remove"></span></span>
      <span class="display-name">Delete</span>
    </a></li>
  </ul>
{% endblock %}

{% block image_file_preview %}
  <!-- Image Preview (new then existing) -->
  <div class="image-list form">
    <span id="image-files-preview"></span><span id="image-files-existing">{% for image in announcement.image_files.all %}<div class="image">
      <a href="{{ image.image_file.url }}" target="_blank" title="Click to open in new tab"><img src="{{ image.image_file_thumbnail.url }}"></a>
    </div>{% endfor %}</span>
  </div>
{% endblock %}

{% block image_link_preview %}
  <!-- Image Preview (new then existing) -->
  <div class="image-list form">
    <span id="image-links-preview"></span><span id="image-links-existing">{% for image in announcement.image_links.all %}<div class="image">
      <a href="{{ image.image_link }}" target="_blank" title="Click to open in new tab"><img src="{{ image.image_file_thumbnail.url }}"></a>
    </div>{% endfor %}</span>
  </div>
{% endblock %}

{% block youtube_video_preview %}
  <!-- YouTube Video Preview (new then existing) -->
  <div id="youtube-videos-preview"></div>
  <div id="youtube-videos-existing">
    {% for video in announcement.youtube_videos.all %}<div data-video-id="{{ video.youtube_video }}" hidden></div>{% endfor %}
  </div>
{% endblock %}

{% block cancel_button_target_url %}{% url 'announcements:detail' announcement.pk %}{% endblock %}
{% block submit_button_id %}submit-announcement-update-form{% endblock %}