api/urls.py
from django.conf.urls import url

from accounts import api_views as accounts_api
from categories import api_views as categories_api
from announcements import api_views as announcements_api
from events import api_views as events_api
from polls import api_views as polls_api
from push_notifications.api.rest_framework import APNSDeviceAuthorizedViewSet
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter
from django.conf.urls import include
app_name = 'api'

router = DefaultRouter()
router.register(r'device/apns', APNSDeviceAuthorizedViewSet)

urlpatterns = [

    url(r'^users/$', accounts_api.UserViewSet.as_view({'get':'list', 'post':'create'}), name='users'),
    url(r'^users/(?P<pk>\d+)$', accounts_api.UserViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='user'),

    url(r'^user_profiles/$', accounts_api.UserProfileViewSet.as_view({'get':'list', 'post':'create'}), name='user_profiles'),
    url(r'^user_profiles/(?P<pk>\d+)$', accounts_api.UserProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='user_profile'),

    url(r'^student_profiles/$', accounts_api.StudentProfileViewSet.as_view({'get':'list', 'post':'create'}), name='student_profiles'),
    url(r'^student_profiles/(?P<pk>\d+)$', accounts_api.StudentProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='student_profile'),

    url(r'^teacher_profiles/$', accounts_api.TeacherProfileViewSet.as_view({'get':'list', 'post':'create'}), name='teacher_profiles'),
    url(r'^teacher_profiles(?P<pk>\d+)/$', accounts_api.TeacherProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='teacher_profile'),

    url(r'^categories/$', categories_api.CategoryViewSet.as_view({'get':'list', 'post':'create'}), name='categories'),
    url(r'^categories/(?P<pk>\d+)$', categories_api.CategoryViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='category'),

    url(r'^announcements/$', announcements_api.AnnouncementViewSet.as_view({'get':'list', 'post':'create'}), name='announcements'),
    url(r'^announcements/(?P<pk>\d+)$', announcements_api.AnnouncementViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='announcement'),

    url(r'^image_files/$', announcements_api.ImageFileViewSet.as_view({'get':'list', 'post':'create'}), name='image_files'),
    url(r'^image_files/(?P<pk>\d+)$', announcements_api.ImageFileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='image_file'),

    url(r'^image_links/$', announcements_api.ImageLinkViewSet.as_view({'get':'list', 'post':'create'}), name='image_links'),
    url(r'^image_links/(?P<pk>\d+)$', announcements_api.ImageLinkViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='image_link'),

    url(r'^youtube_videos/$', announcements_api.YouTubeVideoViewSet.as_view({'get':'list', 'post':'create'}), name='youtube_videos'),
    url(r'^youtube_videos/(?P<pk>\d+)$', announcements_api.YouTubeVideoViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='youtube_video'),

    url(r'^events/$', events_api.EventViewSet.as_view({'get':'list', 'post':'create'}), name='events'),
    url(r'^events(?P<pk>\d+)/$', events_api.EventViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='event'),

    url(r'^polls/$', polls_api.PollViewSet.as_view({'get':'list', 'post':'create'}), name='polls'),
    url(r'^polls/(?P<pk>\d+)$', polls_api.PollViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='poll'),

    url(r'^choices/$', polls_api.ChoiceViewSet.as_view({'get':'list', 'post':'create'}), name='choices'),
    url(r'^choices/(?P<pk>\d+)$', polls_api.ChoiceViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='choice'),

    url(r'^votes/$', polls_api.VoteViewSet.as_view({'get':'list', 'post':'create'}), name='votes'),
    url(r'^votes/(?P<pk>\d+)$', polls_api.VoteViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='vote'),

    # url(r'^', include(router.urls)),
    # url(r'^subjects/$', views_api.SubjectViewSet.as_view({'get':'list', 'post':'create'}), name='subjects'),
    # url(r'^subjects/(?P<pk>\d+)$', views_api.SubjectViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='subject'),
    #
    # url(r'^classes/$', views_api.ClassViewSet.as_view({'get':'list', 'post':'create'}), name='classes'),
    # url(r'^classes/(?P<pk>\d+)$', views_api.ClassViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='class'),
    #
    # url(r'^schedules/$', views_api.ScheduleViewSet.as_view({'get':'list', 'post':'create'}), name='schedules'),
    # url(r'^schedules/(?P<pk>\d+)$', views_api.ScheduleViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='schedule'),

]

polls/urls.py
from django.conf.urls import url

from .views import *

app_name = 'polls'

urlpatterns = [
    url(r'^$', poll_list, name='list'),
    url(r'^create$', poll_create, name='create'),
    url(r'^(?P<pk>\d+)/$', poll_detail, name='detail'),
    url(r'^(?P<pk>\d+)/update$', poll_update, name='update'),
    url(r'^(?P<pk>\d+)/delete$', poll_delete, name='delete'),
    url(r'^generator$', generator, name='generator'),
    url(r'^get_vote/(?P<poll_pk>\d+)$', get_vote, name='get_vote'),
    url(r'^get_vote_count/(?P<choice_pk>\d+)$', get_vote_count, name='get_vote_count'),
]

polls/models.py
from __future__ import unicode_literals

from numpy import random

import pytz
from django.utils import timezone
from datetime import datetime, date, time, timedelta

from django.db import models

from django.core.urlresolvers import reverse

from categories.models import *
from accounts.models import *

from base.models import GetOrNoneManager, lorem_random

################################################################################

class Poll(models.Model):
    content = models.CharField(max_length=200)
    author = models.ForeignKey(UserProfile, related_name="polls", blank=True, null=True, on_delete=models.SET_NULL)
    date_open = models.DateTimeField(auto_now_add=True)
    date_close = models.DateTimeField(blank=True, null=True)
    is_open = models.BooleanField(default=True)
    category = models.ForeignKey(Category, related_name='polls', blank=True, null=True, on_delete=models.SET_NULL)
    rank = models.IntegerField(default=0, blank=True)
    total_vote_count = models.IntegerField(default=0, blank=True)
    # voters = models.ManyToManyField(UserProfile, related_name="polls_submitted", blank=True)
    #TODO: allow visibility to be set for each poll (students, parents, teachers, etc.)

    objects = GetOrNoneManager()

    class Meta:
        ordering = ('is_open', 'rank', '-date_close', '-date_open')

    def __str__(self):
        return "%s (%s)" % (self.content, self.category)

    def save(self, *args, **kwargs):
        if not self.is_open and not self.date_close:
            self.date_close = timezone.now()
        else:
            self.date_close = None
        super(Poll, self).save(*args, **kwargs)

    def get_absolute_url(self):
        return reverse('polls:detail', args=[str(self.pk)])

    def update_vote_count(self):
        total_vote_count = 0
        for c in self.choices.all():
          	total_vote_count += c.vote_count
        self.total_vote_count = total_vote_count
        self.save()

    def get_vote(self, user_profile_pk):
        for c in self.choices.all():
            vote = UserProfile.objects.get(pk=user_profile_pk).votes.get_or_none(choice_id=c.pk)
            if vote:
                return vote
        return None

    def pin(self):
        self.rank = Poll.get_top_rank() + 1
        self.save()

    def unpin(self):
        self.rank = 0
        self.save()

    @classmethod
    def get_top_rank(cls):
        return cls.objects.all().first().rank

    @classmethod
    def clean_ranks(cls):
        pinned = Announcement.objects.filter(rank__gt=0).reverse()
        i = 1
        for a in pinned:
            a.rank = i
            a.save()
            i += 1

    @classmethod
    def generate_random_objects(cls, count, add_votes):
        poll_manager = Poll.objects
        choice_manager = Choice.objects
        user_profiles = UserProfile.objects.all()
        user_profile_count = user_profiles.count()
        if user_profile_count < 100:
            StudentProfile.generate_random_objects(100)
        voter_count = 100
        # Contents
        rand_1 = random.randint(100, size=count) # first word
        rand_2 = random.randint(5, 11, size=count) # length
        # Authors
        rand_3 = random.randint(user_profile_count, size=count)
        # Categories
        categories = Category.objects.all()
        categories_count = categories.count()
        rand_4 = random.randint(categories_count, size=count)
        # Choices
        rand_5 = random.randint(2, 6, size=count)
        # status
        rand_6 = random.randint(3, size=count)

        # Generator loop
        generated_count = 0
        for i in range(0, count):
            # Random Content
            content = lorem_random[rand_1.item(i)] + ' '
            content_length = rand_2.item(i)
            content_rand = random.randint(200, size=content_length)
            for c in range(0, content_length):
                content += lorem_random[content_rand[c]] + ' '
            content += '?'
            # Random Author
            author = user_profiles[rand_3.item(i)]
            # Random Category
            category = categories[rand_4.item(i)]
            # Random Status
            is_open = True
            if rand_6.item(i) == 2:
                is_open = False
            # Create Object
            p = poll_manager.create(content=content, author=author, category=category, is_open=is_open)
            # Random Choices
            choice_count = rand_5.item(i)
            for x in range(0, choice_count):
                choice_content = lorem_random[rand_1.item(i)] + ' '
                choice_length = rand_2.item(i)
                choice_rand = random.randint(200, size=choice_length)
                for y in range(0, choice_length):
                    choice_content += lorem_random[choice_rand[y]] + ' '
                c = choice_manager.create(poll=p, content=choice_content)
            # Random Votes
            vote_count = 0
            if add_votes:
                vote_count = p.generate_random_votes(user_profiles, choice_count, voter_count)
            generated_count += 1
            print('Generated Poll %d (%d choices, %d votes, open: %s)' % (p.pk, choice_count, vote_count, p.is_open))
        return generated_count

    def generate_random_votes(self, user_profiles, choice_count, voter_count):
        vote_manager = Vote.objects
        rand_votes = random.randint(choice_count, size=voter_count)
        choices = self.choices.all()
        vote_counter = 0
        for i in range(0, voter_count):
            voter = user_profiles[i]
            choice = choices[rand_votes.item(i)]
            v = vote_manager.create(poll=self, choice=choice, voter=voter)
            print('Generated Vote %d (Userprofile %d, Choice %d)' % (v.pk, voter.pk, choice.pk))
            vote_counter += 1
        return vote_counter

class Choice(models.Model):
    poll = models.ForeignKey(Poll, related_name='choices', on_delete=models.CASCADE)
    content = models.CharField(max_length=200)
    vote_count = models.IntegerField(default=0, blank=True)

    objects = GetOrNoneManager()

    class Meta:
        ordering = ('poll',)

    def __str__(self):
        return self.content

    def update_vote_count(self):
        self.vote_count = self.votes.count()
        self.save()

class Vote(models.Model):
    voter = models.ForeignKey(UserProfile, related_name='votes', on_delete=models.CASCADE)
    choice = models.ForeignKey(Choice, related_name='votes', on_delete=models.CASCADE)
    poll = models.ForeignKey(Poll, related_name='votes', on_delete=models.CASCADE)

    objects = GetOrNoneManager()

    class Meta:
        ordering = ('poll', 'choice')

    def __str__(self):
        return "%s - %s" %(self.choice, self.voter)

    def save(self, *args, **kwargs):
        p = self.choice.poll
        self.poll = p
        previous_vote = Vote.objects.get_or_none(voter=self.voter, poll=self.poll)
        if previous_vote:
            original_choice = previous_vote.choice
            original_choice.vote_count -= 1
            original_choice.save()
            previous_vote.delete()
        new_choice = Choice.objects.get_or_none(pk=self.choice.pk)
        if new_choice.vote_count % 100 == 0:
          	new_choice.update_vote_count()
        new_choice.vote_count += 1
        new_choice.save()
        p.update_vote_count()
        super(Vote, self).save(*args, **kwargs)

polls/forms.py
from django import forms

from .models import *
from categories.models import *
from base.forms import category_form_field

class PollForm(forms.ModelForm):
    category = category_form_field

    class Meta:
        model = Poll
        fields = ('content', 'category')
        widgets = {
            'content': forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'What is your favorite ice cream flavor?', 'required':'required', 'autofocus':'autofocus'}),
        }

polls/views.py
from .models import *
from .forms import *
from categories.models import *
from push_notifications.models import APNSDevice

from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

@login_required
def poll_list(request):
    hidden = request.user.profile.categories_hidden_polls.values_list('pk', flat=True)
    categories_hidden_polls = Category.objects.filter(pk__in=hidden)
    categories_shown = Category.objects.exclude(pk__in=hidden)
    return render(request, 'polls/poll_list.html', {'categories_shown': categories_shown, 'categories_hidden_polls': categories_hidden_polls})

@login_required
def poll_detail(request, pk):
    # TODO: display poll detail based on status (new, voted, closed)
    poll = Poll.objects.get(pk=pk)
    return render(request, 'polls/poll_detail.html', {'poll': poll})

@staff_member_required()
def poll_create(request):
    form = PollForm(request.POST or None)
    if form.is_valid():
        p = form.save(commit=False)
        p.author = request.user.profile
        p.save()

        choices = request.POST.getlist('choice[]')
        for choice in choices:
            c = Choice(content=choice, poll=p)
            c.save()

        # TODO: Push Notifications
        devices = APNSDevice.objects.all()
        devices.send_message("New Poll!");

        return redirect('polls:list')
    return render(request, 'polls/poll_create.html', {'form': form})

@staff_member_required()
def poll_update(request, pk):
    #TODO: restrict access to either the original author or a superuser admin
    poll = Poll.objects.get(pk=pk)
    form = PollForm(request.POST or None, instance=poll)
    #New Stuff
    if form.is_valid():
        p = form.save()
        new_choices = request.POST.getlist('new-choice[]')
        for choice in new_choices:
            c = Choice(content=choice, poll=p)
            c.save()
        return redirect(poll)
    return render(request, 'polls/poll_update.html', {'form': form, 'poll': poll})

@staff_member_required()
def poll_delete(request, pk):
    #TODO: restrict access to either the original author or a superuser admin
    poll = Poll.objects.get(pk=pk)
    poll.delete()
    return redirect('polls:list')

@staff_member_required()
def pin_poll(request, pk):
    p = Poll.objects.get(pk=pk)
    p.pin()
    return redirect('polls:list')

@staff_member_required()
def unpin_poll(request, pk):
    p = Poll.objects.get(pk=pk)
    p.unpin()
    return redirect('polls:list')

@login_required
def get_vote(request, poll_pk):
    poll = Poll.objects.get_or_none(pk=poll_pk)
    if poll:
        vote = poll.get_vote(request.user.profile.pk)
        if vote:
            return HttpResponse(vote.pk)
    return HttpResponse(-1)

@staff_member_required()
def get_vote_count(request, choice_pk):
    choice = Choice.objects.get_or_none(pk=poll_pk)
    if choice:
        return HttpResponse(choice.vote_count())
    return HttpResponse(-1)

@staff_member_required
def generator(request):
    if request.method == 'POST':
        count = int(request.GET.get('count'))
        add_votes = (request.GET.get('add_votes') == 'true')
        generated_count = Poll.generate_random_objects(count, add_votes=add_votes)
        if (generated_count == count):
            if add_votes:
                return HttpResponse('Success: %d polls were generated with votes' % generated_count)
            else:
                return HttpResponse('Success: %d polls were generated' % generated_count)
        else:
            if add_votes:
                return HttpResponse('Error: %d polls were generated with votes' % generated_count)
            else:
                return HttpResponse('Error: %d polls were generated' % generated_count)

polls/templates/polls/poll_create.html
{% extends "polls/poll_form.html" %}

{% load static from staticfiles %}

{% block title %}Create Poll{% endblock %}

{% block sidebar_poll_create %}selected{% endblock %}

{% block form_id %}poll-create-form{% endblock %}{% block form_url %}{% url 'polls:create' %}{% endblock %}

{% block templates %}
  <template id="choice-input-template">
    <div class="input-group choice-input-wrapper">
      <input required type="text" class="form-control choice-input" name="choice[]" placeholder="{% templatetag openvariable %} placeholder {% templatetag closevariable %}" maxlength="200" data-existing>
      <span class="input-group-btn" tabindex="-1">
        <button class="btn btn-default remove-input" data-flavor="{% templatetag openvariable %} placeholder {% templatetag closevariable %}">
          <span class="glyphicon glyphicon-remove"></span>
        </button>
      </span>
    </div>
  </template>
{% endblock %}
{% block submit_button_id %}submit-poll-create-form{% endblock %}
{% block script %}<script src="{% static 'polls/js/poll_create.js' %}"></script>{% endblock%}

polls/templates/polls/poll_detail.html
{% extends 'base/base.html' %}

{% load static from staticfiles %}

{% block title %}Poll Detail{% endblock %}

{% block masthead_polls %}selected{% endblock %}

{% block sidebar_polls %}selected{% endblock %}

{% block sidebar_extra %}
  <hr class="sidebar-divider">
  <ul id="sidebar-admin-poll">
    <a href="#" class="sidebar-header">Poll</a>
    <li><a href="{% url 'polls:update' poll.pk %}">
      <span class="icon-container"><span class="glyphicon glyphicon-pencil"></span></span>
      <span class="display-name">Make Changes</span>
    </a></li>
    <li><a href="#">
      <span class="icon-container"><span class="glyphicon glyphicon-remove"></span></span>
      <span class="display-name">Delete</span>
    </a></li>
  </ul>
{% endblock %}

{% block content %}
  <div id="poll-{{ poll.pk }}"class="poll-wrapper container-white" data-pk="{{ poll.pk }}" style="border-left: 5px solid {{ poll.category.color|default:'#222222' }}">
    <!-- Poll Content -->
    <div class="content"><h4><a href="{% url 'polls:list' %}" style="font-size:16px; font-weight:500"><div>{{ poll.content }}</div></a></h4></div>
    <!-- Poll Choices -->
    <div class="choice-container">
      {% for choice in poll.choices.all %}
        <div class="choice-option-wrapper row">
          <div class="col-xs-1 text-right">
            <input id="choice-{{ choice.pk }}" type="radio" name="poll-{{ poll.pk }}" value="{{ choice.pk }}">
          </div>
          <div class="col-xs-11">
            <label for="choice-{{ choice.pk }}" class="poll-choice-label">{{ choice.content }}</label>
          </div>
        </div>
      {% endfor %}
    </div>
    <div class="row">
      <div class="col-xs-6">
        <!-- Poll Signature -->
        <div class="signature">
          <span>{{ poll.category|default_if_none:'General' }}</span> &bull;
          <span class="date-open">{{ poll.date_open|date:'M j' }}</span>
        </div>
      </div>
      <div class="col-xs-6">
        <!-- Buttons -->
        <div class="poll-buttons text-right">
          <button type="button" class="btn btn-custom btn-sm poll-vote">Vote</button>
        </div>
      </div>
    </div>
  </div>
{% endblock %}

polls/templates/polls/poll_form.html
{% extends 'base/base.html' %}

{% load static from staticfiles %}

{% block masthead_polls %}selected{% endblock %}

{% block content %}
<div class="container-white">
  <form id="{% block form_id %}{% endblock %}" action="{% block form_url %}{% endblock %}" enctype="multipart/form-data" method="post">{% csrf_token %}
    <!-- Poll Content -->
    <div class="row row-compact">
      <div class="col-xs-2"><div class="form-label">Title</div></div>
      <div class="col-xs-10"><div class="{% if form.content.errors %}has-error{% endif %}">{{ form.content }}</div></div>
    </div><br>
    <!-- Poll Choices -->
    <div class="row row-compact">
      <div class="col-xs-2"><div class="form-label">Choices</div></div>
      <div class="col-xs-10">
        <div id="poll-choices-existing" data-poll-pk="{{ poll.pk }}" data-choice-count="{{ poll.choices.count }}">
          {% for choice in poll.choices.all %}
          <li data-content="{{ choice.content }}" data-choice-pk="{{ choice.pk }}"></li>
          {% endfor %}
        </div>
        <div id="poll-choices-new" class="form-group"></div>
      </div>
    </div><br>
    <!-- Poll Category -->
    <div class="row row-compact">
      <div class="col-xs-2"><div class="form-label">Category</div></div>
      <div class="col-xs-10"><div class="{% if form.category.errors %}has-error{% endif %}">{{ form.category }}</div><hr></div>
    </div>
    <!-- Buttons -->
    <div class="row">
      <div class="col-xs-2"></div>
      <div class="col-xs-4">
        {% block morebuttons %}<button id="poll-choice-add" class="btn btn-sm btn-default" type="button" tabindex="-1"><span class="glyphicon glyphicon-plus"></span> Choice</button>{% endblock %}
      </div>
      <div class="col-xs-6 text-right">
        <a class="btn btn-sm btn-default" href="{% block cancel-button-target-url %}{% url 'polls:list' %}{% endblock %}">Cancel</a>
        <button id="{% block submit_button_id %}{% endblock %}" class="btn btn-sm btn-custom" type="button">{% block submit-button-text %}Publish{% endblock %}</button>
      </div>
    </div>
  </form>
</div>
{% endblock %}
{% block templates %}
  <template id="choice-input-template">
    <div class="input-group choice-input-wrapper">
      <input type="hidden" name="category-{% templatetag openvariable %} index {% templatetag closevariable %}">
      <!--data-choice-pk used when putting-->
      <input required type="text" class="form-control choice-input" name="choice[]" value="{% templatetag openvariable %} content {% templatetag closevariable %}" placeholder="{% templatetag openvariable %} placeholder {% templatetag closevariable %}" maxlength="200" data-choice-pk="{% templatetag openvariable %} pk {% templatetag closevariable %}">
      <span class="input-group-btn" tabindex="-1">
        <!--data-choice-pk used when removing -->
        <button type="button" class="btn btn-default remove-input" data-flavor="{% templatetag openvariable %} placeholder {% templatetag closevariable %}" data-choice-pk="{% templatetag openvariable %} pk {% templatetag closevariable %}">
          <span class="glyphicon glyphicon-remove"></span>
        </button>
      </span>
    </div>
  </template>
{% endblock %}

{% block script %}<script src= "{% static 'polls/js/poll_form.js' %}"></script>{% endblock %}

polls/templates/polls/poll_update.html
{% extends "polls/poll_form.html" %}

{% load static from staticfiles %}

{% block title %}Update Poll{% endblock %}

{% block form_id %}poll-update-form{% endblock %}
{% block form_url %}{% url 'polls:update' poll.pk %}{% endblock %}

{% block sidebar_extra %}
  <hr>
  <ul id="section-admin-poll">
    <a href="#" class="sidebar-section-header">Poll Tools</a>
    <!-- <span class="glyphicon glyphicon-tags"> -->
    <li><a href="{% url 'polls:update' poll.pk %}" class="selected"><span class="icon-container"><span class="glyphicon glyphicon-pencil"></span></span>
      <span class="display-name">Make Changes</span></a></li>
    <li><a href="{% url 'polls:list' %}"><span class="icon-container"><span class="glyphicon glyphicon-remove"></span></span>
      <span class="display-name">Remove</span></a></li>
  </ul>
{% endblock %}

{% block cancel_button_target_url %}{% url 'polls:detail' poll.pk %}{% endblock %}
{% block submit_button_id %}submit-poll-update-form{% endblock %}
{% block script %}<script src="{% static 'polls/js/poll_update.js' %}"></script>{% endblock%}