accounts/urls.py
from django.conf.urls import url

from .views import *

app_name = 'accounts'

urlpatterns = [
    url(r'^parent_register$', parent_register, name='register-parent'),
    url(r'^student_register$', student_register, name='register-student'),
    url(r'^teacher_register$', teacher_register, name='register-teacher'),
    url(r'^login/$', login, name='login'),
    url(r'^logout/$', logout, name='logout'),
    url(r'^(?P<model>[a-z_]+)/generator$', generator, name='generator'),
]

api/urls.py
from django.conf.urls import url

from accounts import api_views as accounts_api
from categories import api_views as categories_api
from announcements import api_views as announcements_api
from events import api_views as events_api
from polls import api_views as polls_api
from push_notifications.api.rest_framework import APNSDeviceAuthorizedViewSet
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter
from django.conf.urls import include
app_name = 'api'

router = DefaultRouter()
router.register(r'device/apns', APNSDeviceAuthorizedViewSet)

urlpatterns = [

    url(r'^users/$', accounts_api.UserViewSet.as_view({'get':'list', 'post':'create'}), name='users'),
    url(r'^users/(?P<pk>\d+)$', accounts_api.UserViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='user'),

    url(r'^user_profiles/$', accounts_api.UserProfileViewSet.as_view({'get':'list', 'post':'create'}), name='user_profiles'),
    url(r'^user_profiles/(?P<pk>\d+)$', accounts_api.UserProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='user_profile'),

    url(r'^student_profiles/$', accounts_api.StudentProfileViewSet.as_view({'get':'list', 'post':'create'}), name='student_profiles'),
    url(r'^student_profiles/(?P<pk>\d+)$', accounts_api.StudentProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='student_profile'),

    url(r'^teacher_profiles/$', accounts_api.TeacherProfileViewSet.as_view({'get':'list', 'post':'create'}), name='teacher_profiles'),
    url(r'^teacher_profiles(?P<pk>\d+)/$', accounts_api.TeacherProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='teacher_profile'),

    url(r'^categories/$', categories_api.CategoryViewSet.as_view({'get':'list', 'post':'create'}), name='categories'),
    url(r'^categories/(?P<pk>\d+)$', categories_api.CategoryViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='category'),

    url(r'^announcements/$', announcements_api.AnnouncementViewSet.as_view({'get':'list', 'post':'create'}), name='announcements'),
    url(r'^announcements/(?P<pk>\d+)$', announcements_api.AnnouncementViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='announcement'),

    url(r'^image_files/$', announcements_api.ImageFileViewSet.as_view({'get':'list', 'post':'create'}), name='image_files'),
    url(r'^image_files/(?P<pk>\d+)$', announcements_api.ImageFileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='image_file'),

    url(r'^image_links/$', announcements_api.ImageLinkViewSet.as_view({'get':'list', 'post':'create'}), name='image_links'),
    url(r'^image_links/(?P<pk>\d+)$', announcements_api.ImageLinkViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='image_link'),

    url(r'^youtube_videos/$', announcements_api.YouTubeVideoViewSet.as_view({'get':'list', 'post':'create'}), name='youtube_videos'),
    url(r'^youtube_videos/(?P<pk>\d+)$', announcements_api.YouTubeVideoViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='youtube_video'),

    url(r'^events/$', events_api.EventViewSet.as_view({'get':'list', 'post':'create'}), name='events'),
    url(r'^events(?P<pk>\d+)/$', events_api.EventViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='event'),

    url(r'^polls/$', polls_api.PollViewSet.as_view({'get':'list', 'post':'create'}), name='polls'),
    url(r'^polls/(?P<pk>\d+)$', polls_api.PollViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='poll'),

    url(r'^choices/$', polls_api.ChoiceViewSet.as_view({'get':'list', 'post':'create'}), name='choices'),
    url(r'^choices/(?P<pk>\d+)$', polls_api.ChoiceViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='choice'),

    url(r'^votes/$', polls_api.VoteViewSet.as_view({'get':'list', 'post':'create'}), name='votes'),
    url(r'^votes/(?P<pk>\d+)$', polls_api.VoteViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='vote'),

    # url(r'^', include(router.urls)),
    # url(r'^subjects/$', views_api.SubjectViewSet.as_view({'get':'list', 'post':'create'}), name='subjects'),
    # url(r'^subjects/(?P<pk>\d+)$', views_api.SubjectViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='subject'),
    #
    # url(r'^classes/$', views_api.ClassViewSet.as_view({'get':'list', 'post':'create'}), name='classes'),
    # url(r'^classes/(?P<pk>\d+)$', views_api.ClassViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='class'),
    #
    # url(r'^schedules/$', views_api.ScheduleViewSet.as_view({'get':'list', 'post':'create'}), name='schedules'),
    # url(r'^schedules/(?P<pk>\d+)$', views_api.ScheduleViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='schedule'),

]

accounts/models.py
from __future__ import unicode_literals

from numpy import random

from datetime import datetime, date, time, timedelta

from django.db import models
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse

from categories.models import *

from base.models import GetOrNoneManager, mobile_validator, student_id_validator, first_names, last_names

################################################################################

class UserProfile(models.Model):
    user = models.OneToOneField(User, related_name='profile', null=True)
    # TODO: set mobile to unique = True in production
    mobile = models.CharField("Phone Number", max_length=10, validators=[mobile_validator])
    # TODO: create a signal (or just update save function of related model) that automatically sets these values when a related student/teacher profile object is saved
    is_student = models.BooleanField(default=False)
    is_teacher = models.BooleanField(default=False)

    categories_hidden_announcements = models.ManyToManyField(Category, related_name="user_profiles_with_category_hidden_for_announcements", blank=True)
    categories_hidden_events = models.ManyToManyField(Category, related_name="user_profiles_with_category_hidden_for_events", blank=True)
    categories_hidden_polls = models.ManyToManyField(Category, related_name="user_profiles_with_category_hidden_for_polls", blank=True)

    objects = GetOrNoneManager()

    def __str__(self):
        return self.user.get_full_name()

    def save(self, *args, **kwargs):
        if not self.pk:
            self.pk = self.user.pk
        super(UserProfile, self).save(*args, **kwargs)

class StudentProfile(models.Model):
    FRESHMAN = 0
    SOPHOMORE = 1
    JUNIOR = 2
    SENIOR = 3
    GRADE_LEVEL_CHOICES = (
        (FRESHMAN, 'Freshman'),
        (SOPHOMORE, 'Sophomore'),
        (JUNIOR, 'Junior'),
        (SENIOR, 'Senior'),
    )
    user_profile = models.OneToOneField(UserProfile, related_name='student_profile', null=True)
    # TODO: set student_id to unique = True in production
    student_id = models.CharField("Student ID", max_length=10, validators=[student_id_validator])
    grade_level = models.IntegerField("Grade Level", default=FRESHMAN, choices=GRADE_LEVEL_CHOICES)

    objects = GetOrNoneManager()

    def __str__(self):
        return '%s - student profile' % self.user_profile

    def save(self, *args, **kwargs):
        if not self.pk:
            self.pk = self.user_profile.user.pk
        super(StudentProfile, self).save(*args, **kwargs)

    @classmethod
    def generate_random_objects(cls, count):
        rand_1 = random.randint(140, size=count)
        rand_2 = random.randint(140, size=count)
        rand_3 = random.randint(1100000000, 1100999999, size=count)
        rand_4 = random.randint(3, size=count)

        user_pk = User.objects.latest('pk').pk + 1
        generated_count = 0
        for i in range(0, count):
            first_name = first_names[rand_1.item(i)]
            last_name = last_names[rand_2.item(i)]
            student_id = rand_3.item(i)
            grade_level = rand_4.item(i)
            user = User.objects.create_user(
                username=user_pk,
                password=user_pk,
                first_name=first_name,
                last_name=last_name,
            )
            user_profile = UserProfile.objects.create(
                user=user,
                mobile='6787901506',
                is_student=True,
            )
            student_profile= StudentProfile.objects.create(
                user_profile=user_profile,
                student_id = student_id,
                grade_level=grade_level,
            )
            user_pk += 1
            generated_count += 1
            print('Generated StudentProfile %d (UserProfile %d User %d)' %(student_profile.pk, user_profile.pk, user.pk))
        return generated_count

class TeacherProfile(models.Model):
    user_profile = models.OneToOneField(UserProfile, related_name='teacher_profile', null=True)
    room = models.CharField("Room Number", unique=True, max_length=6)

    objects = GetOrNoneManager()

    def __str__(self):
        return '%s - teacher profile' % self.user_profile

    def save(self, *args, **kwargs):
        if not self.pk:
            self.pk = self.user_profile.user.pk
        super(TeacherProfile, self).save(*args, **kwargs)

accounts/forms.py
from django import forms

from .models import *
from django.contrib.auth.models import User

class UserForm(forms.ModelForm):
    first_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'First Name', 'autofocus':'autofocus'}))
    last_name = forms.CharField(required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Last Name'}))
    email = forms.EmailField(required=True, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'doej1234@chsknights.com'}))

    class Meta:
        model = User
        fields = ('username', 'password', 'first_name', 'last_name', 'email')
        widgets = {
            'username': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Username'}),
            'password': forms.widgets.PasswordInput(attrs={'class':'form-control', 'placeholder':'Password'}),
        }

class UserProfileForm(forms.ModelForm):

    class Meta:
        model = UserProfile
        fields = ('mobile',)
        widgets = {
            'mobile': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Phone Number'}),
        }

class StudentProfileForm(forms.ModelForm):

    class Meta:
        model = StudentProfile
        fields = ('student_id', 'grade_level')
        widgets = {
            'student_id': forms.TextInput(attrs={'class':'form-control', 'placeholder':'1100987654'}),
            'grade_level': forms.Select(attrs={'class':'form-control', 'placeholder':'Grade Level'}),
        }

class TeacherProfileForm(forms.ModelForm):

    class Meta:
        model = TeacherProfile
        fields = ('room',)
        widgets = {
            'room': forms.TextInput(attrs={'class':'form-control', 'placeholder':'Room Number'}),
        }

accounts/views.py
from .models import *
from .forms import *

from django.http import HttpResponse
from django.shortcuts import render, redirect

from django.contrib.auth.decorators import login_required
from django.contrib.admin.views.decorators import staff_member_required

from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout

def parent_register(request):
    userForm = UserForm(request.POST or None)
    userProfileForm = UserProfileForm(request.POST or None)
    if userForm.is_valid() and userProfileForm.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = userForm.save(commit=False)
        user.set_password(password)
        user.save()
        userProfile = userProfileForm.save(commit=False)
        userProfile.user = user
        userProfile.save()
        user = authenticate(username=username, password=password)
        auth_login(request, user)
        return redirect('base:index')
    return render(request, 'accounts/register_parent.html', {'userForm': userForm, 'userProfileForm': userProfileForm})

def student_register(request):
    userForm = UserForm(request.POST or None)
    userProfileForm = UserProfileForm(request.POST or None)
    studentProfileForm = StudentProfileForm(request.POST or None)
    if userForm.is_valid() and userProfileForm.is_valid() and studentProfileForm.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = userForm.save(commit=False)
        user.set_password(password)
        user.save()
        userProfile = userProfileForm.save(commit=False)
        userProfile.user = user
        userProfile.is_student = True
        userProfile.save()
        studentProfile = studentProfileForm.save(commit=False)
        studentProfile.user_profile = userProfile
        studentProfile.save()
        user = authenticate(username=username, password=password)
        auth_login(request, user)
        return redirect('base:index')
    return render(request, 'accounts/register_student.html', {'userForm': userForm, 'userProfileForm': userProfileForm, 'studentProfileForm': studentProfileForm})

def teacher_register(request):
    userForm = UserForm(request.POST or None)
    userProfileForm = UserProfileForm(request.POST or None)
    teacherProfileForm = TeacherProfileForm(request.POST or None)
    if userForm.is_valid() and userProfileForm.is_valid() and teacherProfileForm.is_valid():
        username = request.POST.get('username')
        password = request.POST.get('password')
        user = userForm.save(commit=False)
        user.set_password(password)
        user.save()
        userProfile = userProfileForm.save(commit=False)
        userProfile.user = user
        userProfile.is_teacher = true
        userProfile.save()
        teacherProfile = teacherProfileForm.save(commit=False)
        teacherProfile.user_profile = userProfile
        teacherProfile.save()
        user = authenticate(username=username, password=password)
        auth_login(request, user)
        return redirect('base:index')
    return render(request, 'accounts/register_teacher.html', {'userForm': userForm, 'userProfileForm': userProfileForm, 'teacherProfileForm': teacherProfileForm})

def login(request):
    if request.user.is_authenticated():
        return redirect('base:index')
    username = request.POST.get('username')
    password = request.POST.get('password')
    target_url = request.GET.get('next')
    user = authenticate(username=username, password=password)
    if user:
        auth_login(request, user)
        if target_url:
            return redirect(target_url)
        return redirect('base:index')
    return render(request, 'accounts/login.html')

@login_required
def logout(request):
    auth_logout(request)
    return redirect('base:index')

@staff_member_required
def generator(request, model):
    if request.method == 'POST':
        count = int(request.GET.get('count'))
        generated_count = 0
        if model == 'student_profiles':
            generated_count = StudentProfile.generate_random_objects(count)
        if (generated_count == count):
            return HttpResponse('Success: %d %s were generated' % (generated_count, model))
        else:
            return HttpResponse('Error: %d %s were generated' % (generated_count, model))

accounts/templates/accounts/login.html
{% extends 'base/base.html' %}

{% load staticfiles %}

{% block script %}<script src="{% static 'accounts/js/login.js' %}"></script>{% endblock %}

accounts/templates/accounts/register_parent.html
{% extends 'base/base_register.html' %}

{% load static from staticfiles %}

{% block title %}Parent Registration{% endblock %}

{% block header %}Parent Registration{% endblock %}

{% block masthead_bottom %}
  {{ block.super }}
  <li><a href="#" class="selected">Parent Registration</a></li>
{% endblock %}

{% block sidebar_parent_register %}selected{% endblock %}

{% block register_form_id %}parent-register-form{% endblock %}
{% block register_form_url %}{% url 'accounts:register-parent' %}{% endblock %}
{% block submit_button_id %}submit-parent-register-form{% endblock %}
{% block submit_button_text %}Create Parent Account{% endblock %}

{% block register_form_extra_fields %}
  <div class="row register-form-row">
    <div class="col-xs-3"><div class="form-label">Email</div></div>
    <div class="col-xs-9">
      <div class="has-feedback {% if userForm.email.errors %}has-error{% elif userForm.is_bound %}has-success{% endif %}" title="{{ userForm.email.errors.as_text }}" data-toggle="tooltip" data-placement="right" data-trigger="focus">
        {{ userForm.email }}
        {% if userForm.email.errors %}<span class="glyphicon glyphicon-remove form-control-feedback"></span>
        {% elif userForm.is_bound %}<span class="glyphicon glyphicon-ok form-control-feedback"></span>{% endif %}
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/register_student.html
{% extends 'base/base_register.html' %}

{% load static from staticfiles %}

{% block title %}Student Registration{% endblock %}

{% block header %}Student Registration{% endblock %}

{% block masthead_bottom %}
  {{ block.super }}
  <li><a href="#" class="selected">Student Registration</a></li>
{% endblock %}

{% block sidebar_student_register %}selected{% endblock %}

{% block register_form_id %}student-register-form{% endblock %}
{% block register_form_url %}{% url 'accounts:register-student' %}{% endblock %}
{% block submit_button_id %}submit-student-register-form{% endblock %}
{% block submit_button_text %}Create Student Account{% endblock %}

{% block register_form_extra_fields %}
  <div class="row register-form-row">
    <div class="col-xs-3"><div class="form-label">School Email</div></div>
    <div class="col-xs-9">
      <div class="has-feedback {% if userForm.email.errors %}has-error{% elif userForm.is_bound %}has-success{% endif %}" title="{{ userForm.email.errors.as_text }}" data-toggle="tooltip" data-placement="right" data-trigger="focus">
        {{ userForm.email }}
        {% if userForm.email.errors %}<span class="glyphicon glyphicon-remove form-control-feedback"></span>
        {% elif userForm.is_bound %}<span class="glyphicon glyphicon-ok form-control-feedback"></span>{% endif %}
      </div>
    </div>
  </div>
  <div class="row register-form-row">
    <div class="col-xs-3"><div class="form-label">Student ID</div></div>
    <div class="col-xs-9">
      <div class="has-feedback {% if studentProfileForm.student_id.errors %}has-error{% elif studentProfileForm.is_bound %}has-success{% endif %}" title="{{ studentProfileForm.student_id.errors.as_text }}" data-toggle="tooltip" data-placement="right" data-trigger="focus">
        {{ studentProfileForm.student_id }}
        {% if studentProfileForm.student_id.errors %}<span class="glyphicon glyphicon-remove form-control-feedback"></span>
        {% elif studentProfileForm.is_bound %}<span class="glyphicon glyphicon-ok form-control-feedback"></span>{% endif %}
      </div>
    </div>
  </div>
  <div class="row register-form-row">
    <div class="col-xs-3"><div class="form-label">Grade Level</div></div>
    <div class="col-xs-9">
      <div class="has-feedback {% if studentProfileForm.grade_level.errors %}has-error{% elif studentProfileForm.is_bound %}has-success{% endif %}" title="{{ studentProfileForm.grade_level.errors.as_text }}" data-toggle="tooltip" data-placement="right" data-trigger="focus">
        {{ studentProfileForm.grade_level }}
        {% if studentProfileForm.grade_level.errors %}<span class="glyphicon glyphicon-remove form-control-feedback"></span>
        {% elif studentProfileForm.is_bound %}<span class="glyphicon glyphicon-ok form-control-feedback"></span>{% endif %}
      </div>
    </div>
  </div>
{% endblock %}

accounts/templates/accounts/register_teacher.html
{% extends 'base/base_register.html' %}

{% load static from staticfiles %}

{% block title %}Teacher Registration{% endblock %}

{% block header %}Teacher Registration{% endblock %}

{% block masthead_bottom %}
  {{ block.super }}
  <li><a href="#" class="selected">Teacher Registration</a></li>
{% endblock %}

{% block sidebar_teacher_register %}selected{% endblock %}

{% block register_form_id %}teacher-register-form{% endblock %}
{% block register_form_url %}{% url 'accounts:register-teacher' %}{% endblock %}
{% block submit_button_id %}submit-teacher-register-form{% endblock %}
{% block submit_button_text %}Create Teacher Account{% endblock %}

{% block register_form_extra_fields %}
  <div class="row register-form-row">
    <div class="col-xs-3"><div class="form-label">School Email</div></div>
    <div class="col-xs-9">
      <div class="has-feedback {% if userForm.email.errors %}has-error{% elif userForm.is_bound %}has-success{% endif %}" title="{{ userForm.email.errors.as_text }}" data-toggle="tooltip" data-placement="right" data-trigger="focus">
        {{ userForm.email }}
        {% if userForm.email.errors %}<span class="glyphicon glyphicon-remove form-control-feedback"></span>
        {% elif userForm.is_bound %}<span class="glyphicon glyphicon-ok form-control-feedback"></span>{% endif %}
      </div>
    </div>
  </div>
  <div class="row register-form-row">
    <div class="col-xs-3"><div class="form-label">Room Number</div></div>
    <div class="col-xs-9">
      <div class="has-feedback {% if teacherProfileForm.room.errors %}has-error{% elif teacherProfileForm.is_bound %}has-success{% endif %}" title="{{ teacherProfileForm.room.errors.as_text }}" data-toggle="tooltip" data-placement="right" data-trigger="focus">
        {{ teacherProfileForm.room }}
        {% if teacherProfileForm.room.errors %}<span class="glyphicon glyphicon-remove form-control-feedback"></span>
        {% elif teacherProfileForm.is_bound %}<span class="glyphicon glyphicon-ok form-control-feedback"></span>{% endif %}
      </div>
    </div>
  </div>
{% endblock %}