api/urls.py
from django.conf.urls import url

from accounts import api_views as accounts_api
from categories import api_views as categories_api
from announcements import api_views as announcements_api
from events import api_views as events_api
from polls import api_views as polls_api
from push_notifications.api.rest_framework import APNSDeviceAuthorizedViewSet
from rest_framework.urlpatterns import format_suffix_patterns
from rest_framework.routers import DefaultRouter
from django.conf.urls import include
app_name = 'api'

router = DefaultRouter()
router.register(r'device/apns', APNSDeviceAuthorizedViewSet)

urlpatterns = [

    url(r'^users/$', accounts_api.UserViewSet.as_view({'get':'list', 'post':'create'}), name='users'),
    url(r'^users/(?P<pk>\d+)$', accounts_api.UserViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='user'),

    url(r'^user_profiles/$', accounts_api.UserProfileViewSet.as_view({'get':'list', 'post':'create'}), name='user_profiles'),
    url(r'^user_profiles/(?P<pk>\d+)$', accounts_api.UserProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='user_profile'),

    url(r'^student_profiles/$', accounts_api.StudentProfileViewSet.as_view({'get':'list', 'post':'create'}), name='student_profiles'),
    url(r'^student_profiles/(?P<pk>\d+)$', accounts_api.StudentProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='student_profile'),

    url(r'^teacher_profiles/$', accounts_api.TeacherProfileViewSet.as_view({'get':'list', 'post':'create'}), name='teacher_profiles'),
    url(r'^teacher_profiles(?P<pk>\d+)/$', accounts_api.TeacherProfileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='teacher_profile'),

    url(r'^categories/$', categories_api.CategoryViewSet.as_view({'get':'list', 'post':'create'}), name='categories'),
    url(r'^categories/(?P<pk>\d+)$', categories_api.CategoryViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='category'),

    url(r'^announcements/$', announcements_api.AnnouncementViewSet.as_view({'get':'list', 'post':'create'}), name='announcements'),
    url(r'^announcements/(?P<pk>\d+)$', announcements_api.AnnouncementViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='announcement'),

    url(r'^image_files/$', announcements_api.ImageFileViewSet.as_view({'get':'list', 'post':'create'}), name='image_files'),
    url(r'^image_files/(?P<pk>\d+)$', announcements_api.ImageFileViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='image_file'),

    url(r'^image_links/$', announcements_api.ImageLinkViewSet.as_view({'get':'list', 'post':'create'}), name='image_links'),
    url(r'^image_links/(?P<pk>\d+)$', announcements_api.ImageLinkViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='image_link'),

    url(r'^youtube_videos/$', announcements_api.YouTubeVideoViewSet.as_view({'get':'list', 'post':'create'}), name='youtube_videos'),
    url(r'^youtube_videos/(?P<pk>\d+)$', announcements_api.YouTubeVideoViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='youtube_video'),

    url(r'^events/$', events_api.EventViewSet.as_view({'get':'list', 'post':'create'}), name='events'),
    url(r'^events(?P<pk>\d+)/$', events_api.EventViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='event'),

    url(r'^polls/$', polls_api.PollViewSet.as_view({'get':'list', 'post':'create'}), name='polls'),
    url(r'^polls/(?P<pk>\d+)$', polls_api.PollViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='poll'),

    url(r'^choices/$', polls_api.ChoiceViewSet.as_view({'get':'list', 'post':'create'}), name='choices'),
    url(r'^choices/(?P<pk>\d+)$', polls_api.ChoiceViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='choice'),

    url(r'^votes/$', polls_api.VoteViewSet.as_view({'get':'list', 'post':'create'}), name='votes'),
    url(r'^votes/(?P<pk>\d+)$', polls_api.VoteViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='vote'),

    # url(r'^', include(router.urls)),
    # url(r'^subjects/$', views_api.SubjectViewSet.as_view({'get':'list', 'post':'create'}), name='subjects'),
    # url(r'^subjects/(?P<pk>\d+)$', views_api.SubjectViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='subject'),
    #
    # url(r'^classes/$', views_api.ClassViewSet.as_view({'get':'list', 'post':'create'}), name='classes'),
    # url(r'^classes/(?P<pk>\d+)$', views_api.ClassViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='class'),
    #
    # url(r'^schedules/$', views_api.ScheduleViewSet.as_view({'get':'list', 'post':'create'}), name='schedules'),
    # url(r'^schedules/(?P<pk>\d+)$', views_api.ScheduleViewSet.as_view({'get': 'retrieve', 'put':'partial_update', 'delete':'destroy'}), name='schedule'),

]

base/urls.py
from django.conf.urls import url

from django.views.generic.base import RedirectView

from .views import *

app_name='base'

urlpatterns = [
    # Index (redirect to announcements list)
    url(r'^$', RedirectView.as_view(pattern_name='announcements:list'), name='index'),
    # Generator
    url(r'^generator/$', generator, name='generator'),
]

categories/urls.py
from django.conf.urls import url

from .views import *

app_name = 'categories'

urlpatterns = [
    url(r'^$', category_list, name='list'),
    url(r'^merge/$', category_merge, name='merge'),
]

events/urls.py
from django.conf.urls import url

from .views import *

app_name = 'events'

urlpatterns = [
    url(r'^$', event_list, name='list'),
    url(r'^create$', event_create, name='create'),
    url(r'^(?P<pk>\d+)/$', event_detail, name='detail'),
    url(r'^(?P<pk>\d+)/update$', event_update, name='update'),
    url(r'^(?P<pk>\d+)/delete$', event_delete, name='delete'),
    url(r'^generator$', generator, name='generator'),
]

polls/urls.py
from django.conf.urls import url

from .views import *

app_name = 'polls'

urlpatterns = [
    url(r'^$', poll_list, name='list'),
    url(r'^create$', poll_create, name='create'),
    url(r'^(?P<pk>\d+)/$', poll_detail, name='detail'),
    url(r'^(?P<pk>\d+)/update$', poll_update, name='update'),
    url(r'^(?P<pk>\d+)/delete$', poll_delete, name='delete'),
    url(r'^generator$', generator, name='generator'),
    url(r'^get_vote/(?P<poll_pk>\d+)$', get_vote, name='get_vote'),
    url(r'^get_vote_count/(?P<choice_pk>\d+)$', get_vote_count, name='get_vote_count'),
]

categories/models.py
from __future__ import unicode_literals

from django.db import models
from django.core.urlresolvers import reverse

from colorful.fields import RGBColorField

from base.models import GetOrNoneManager

################################################################################

class Category(models.Model):
    COLOR_CHOICES = [
        '#f2f3f4', '#f3c300', '#875692', '#f38400', '#a1caf1', '#be0032', '#c2b280',
        '#848482', '#008856', '#e68fac', '#0067a5', '#f99379', '#604e97', '#f6a600',
        '#b3446c', '#dcd300', '#882d17', '#8db600', '#654522', '#e25822', '#2b3d26',
    ]
    name = models.CharField(max_length=30)
    color = RGBColorField(unique=True, colors=COLOR_CHOICES)

    objects = GetOrNoneManager()

    class Meta:
        ordering = ('name',)
        verbose_name_plural = "categories"

    def __str__(self):
        return self.name

    @classmethod
    def merge(cls, categories, new_name=None, new_color=None):
        count = len(categories)
        if count > 0:
            first = categories[0]
            for i in range(1, count):
                categories[i].announcements.all().update(category=first)
                categories[i].events.all().update(category=first)
                categories[i].polls.all().update(category=first)
                categories[i].delete()
            # Keep first category's name and color by default
            if new_name:
                first.name = new_name
            if new_color:
                first.color = new_color
            first.save()
            return True

categories/forms.py
# from django import forms

categories/views.py
from .models import *

from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.admin.views.decorators import staff_member_required

@staff_member_required()
def category_list(request):
    if request.method == 'POST':
        categories = request.POST.lists()
        for k,c in categories:
            if k.startswith('category'):
                pk = c[0]
                name = c[1]
                color = c[2]
                if pk == 'new':
                    new_c = Category(name=name, color=color)
                else:
                    new_c = Category.objects.get_or_none(pk=int(pk))
                    new_c.name = name
                    new_c.color = color
                new_c.save()
    categories = Category.objects.all()
    return render(request, 'categories/category_list.html', {'categories': categories})

@staff_member_required
def category_merge(request):
    category_pks = request.GET.getlist('category')
    categories = Category.objects.filter(pk__in=category_pks)
    new_name = request.GET.get('new_name')
    new_color = request.GET.get('new_color')
    if categories:
        Category.merge(categories=categories, new_name=new_name, new_color=new_color)
        return redirect('categories:list')

    categories = Category.objects.all()
    return render(request, 'categories/category_merge.html', {'categories': categories})

categories/templates/categories/category_list.html
{% extends 'base/base.html' %}

{% load static from staticfiles %}

{% block title %}Categories{% endblock %}

{% block header %}Categories{% endblock %}

{% block masthead_bottom %}
  <li><a href="{% url 'base:index' %}">Trending</a></li>
  <li><a href="{% url 'announcements:list' %}">Announcements</a></li>
  <li><a href="{% url 'events:list' %}">Events</a></li>
  <li><a href="{% url 'polls:list' %}">Polls</a></li>
{% endblock %}

{% block sidebar_category_list %}selected{% endblock %}

{% block content %}
  <div class="row">
    <div class="col-xs-8 col-xs-offset-2">
      <div class="container-white">
        <form id="category-list-form" action="{% url 'categories:list' %}" method="post">{% csrf_token %}
          <!-- Category List -->
          <div id="categories" class="form-group">
            {% for c in categories %}
              <li data-name="{{ c.name }}" data-color="{{ c.color }}" data-pk="{{ c.pk }}" hidden></li>
              {% if forloop.last %}<div id="initial-count" hidden>{{ forloop.counter }}</div>{% endif %}
            {% endfor %}
          </div><hr>
          <!-- Buttons -->
          <div class="row">
            <div class="col-xs-1"></div>
            <div class="col-xs-5">
              {% block morebuttons %}<button id="category-add" class="btn btn-sm btn-default" type="button" tabindex="-1"><span class="glyphicon glyphicon-plus"></span> Category</button>{% endblock %}
            </div>
            <div class="col-xs-6 text-right">
              <a class="btn btn-sm btn-default" href="{% block cancel_button_target_url %}{% url 'base:index' %}{% endblock %}">Cancel</a>
              <button id="{% block submit_button_id %}submit-category-list-form{% endblock %}" class="btn btn-sm btn-custom" type="button">{% block submit_button_text %}Save{% endblock %}</button>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>

  <!-- Color Choices -->
  <datalist id="datalist-color-choices">
    <option>#f2f3f4</option><option>#f3c300</option><option>#875692</option>
    <option>#f38400</option><option>#a1caf1</option><option>#be0032</option>
    <option>#c2b280</option><option>#848482</option><option>#008856</option>
    <option>#e68fac</option><option>#0067a5</option><option>#f99379</option>
    <option>#604e97</option><option>#f6a600</option><option>#b3446c</option>
    <option>#dcd300</option><option>#882d17</option><option>#8db600</option>
    <option>#654522</option><option>#e25822</option><option>#2b3d26</option>
  </datalist>
{% endblock %}

{% block templates %}
  <template id="old-category-template">
    <div class="input-group-wrapper">
      <input type="hidden" name="category-{% templatetag openvariable %} index {% templatetag closevariable %}" value="{% templatetag openvariable %} pk {% templatetag closevariable %}">
      <div class="row">
        <div class="col-xs-1">
        </div>
        <div class="col-xs-11">
          <div class="input-group">
            <input type="text" class="form-control category-name-input"
              name="category-{% templatetag openvariable %} index {% templatetag closevariable %}"
              value="{% templatetag openvariable %} name {% templatetag closevariable %}"
              placeholder="Category Name" maxlength="30" required>
            <span class="input-group-btn"><input required type="color" class="form-control btn btn-default color-input" maxlength="7"
              list="datalist-color-choices"
              name="category-{% templatetag openvariable %} index {% templatetag closevariable %}"
              value="{% templatetag openvariable %} color {% templatetag closevariable %}"
              data-old-value="{% templatetag openvariable %} color {% templatetag closevariable %}">
            </span>
          </div>
        </div>
      </div>
    </div>
  </template>
  <template id="new-category-template">
    <div class="input-group-wrapper">
      <input type="hidden" name="category-{% templatetag openvariable %} index {% templatetag closevariable %}" value="{% templatetag openvariable %} pk {% templatetag closevariable %}">
      <div class="row">
        <div class="col-xs-1">
          <button type="button" class="close remove_field" title="Remove" data-toggle="tooltip" data-placement="top"><span>&times;</span></button>
        </div>
        <div class="col-xs-11">
          <div class="input-group">
            <input type="text" class="form-control category-name-input"
              name="category-{% templatetag openvariable %} index {% templatetag closevariable %}"
              placeholder="Category Name" maxlength="30" required>
            <span class="input-group-btn"><input required type="color" class="form-control btn btn-default" maxlength="7"
              list="datalist-color-choices"
              name="category-{% templatetag openvariable %} index {% templatetag closevariable %}"
              value="{% templatetag openvariable %} color {% templatetag closevariable %}"
              data-old-value="{% templatetag openvariable %} color {% templatetag closevariable %}">
            </span>
          </div>
        </div>
      </div>
    </div>
  </template>
{% endblock %}

{% block script %}<script src="{% static 'categories/js/category_list.js' %}"></script>{% endblock %}

categories/templates/categories/category_merge.html
{% extends 'base/base.html' %}

{% load static from staticfiles %}

{% block title %}Categories{% endblock %}

{% block header %}Categories{% endblock %}

{% block masthead_bottom %}
  <li><a href="{% url 'announcements:list' %}">Announcements</a></li>
  <li><a href="{% url 'events:list' %}">Events</a></li>
  <li><a href="{% url 'polls:list' %}">Polls</a></li>
{% endblock %}

{% block sidebar_category_merge %}selected{% endblock %}

{% block content %}
      <div class="container-white">
        <form id="category-merge-form">
          <div id="category-merge-set-form">
            <div class="row">
              <!-- Category List -->
              <div class="col-sm-6">
                <h5 id="left-instruction">Select categories:</h5>
                <div id="categories" class="form-group"></div>
              </div>

              <div class="col-sm-6">
                <h5 id="right-instruction">Merge into:</h5>
                  <!-- Merged Category Name -->
                  <div class="row">
                    <div class="col-sm-2">
                      <div class="form-label">Name</div>
                    </div>
                    <div class="col-sm-10">
                      <input id="category-new-name-input" type="text" class="form-control category-name-input"
                        name="category-{% templatetag openvariable %} index {% templatetag closevariable %}"
                        placeholder="Category Name" maxlength="30" required>
                    </div>
                  </div>
                  <!-- Merged Category Color -->
                  <div class-"row">
                    <div class="col-sm-2">
                      <div class="form-label">Color</div>
                    </div>
                    <div class="col-sm-10">
                      <input id="category-new-color-input" required type="color" class="form-control btn btn-default" maxlength="7" list="datalist-color-choices">
                    </div>
                  </div>
                </div>
              </div>
              <!-- Buttons -->
              <div class="row text-right">
                  <a class="btn btn-sm btn-default" href="{% block cancel_button_target_url %}{% url 'base:index' %}{% endblock %}">Cancel</a>
                  <a id="continue-category-merge" class="btn btn-sm btn-primary">Continue</a>
              </div>
          </div>
          </form>
        </div>


  <!-- Color Choices -->
  <datalist id="datalist-color-choices">
    <option>#f2f3f4</option><option>#f3c300</option><option>#875692</option>
    <option>#f38400</option><option>#a1caf1</option><option>#be0032</option>
    <option>#c2b280</option><option>#848482</option><option>#008856</option>
    <option>#e68fac</option><option>#0067a5</option><option>#f99379</option>
    <option>#604e97</option><option>#f6a600</option><option>#b3446c</option>
    <option>#dcd300</option><option>#882d17</option><option>#8db600</option>
    <option>#654522</option><option>#e25822</option><option>#2b3d26</option>
  </datalist>
{% endblock %}

{% block templates %}
  <template id="confirm-merge-template">
    <div id="category-merge-confirm-form">
      <div class="row">
        <!-- Category List -->
        <div id="selected-categories" class="col-sm-4"></div>
        <div class="col-sm-4"><h5>Will be merged into</h5></div>
        <div class="col-sm-4">
          <span id="category-new-color" class="icon-container" style="color:{% templatetag openvariable %} newColor {% templatetag closevariable %};" data-color="{% templatetag openvariable %} newColor {% templatetag closevariable %}"><span class="glyphicon glyphicon-tag"></span></span><label id="category-new-name" style="font-weight:normal;" class="category-label">{% templatetag openvariable %} newName {% templatetag closevariable %}</label>
        </div>
      </div>
      <!-- Buttons -->
      <div class="row text-right">
          <a id="back-category-merge-form" class="btn btn-sm btn-default">Back</a>
          <a id="submit-category-merge-form" class="btn btn-sm btn-primary">Merge</a>
      </div>
    </div>
  </template>
  <template id="old-category-template">
      <div class="row">
        <div class="col-sm-1 text-right">
          <input id="category-{% templatetag openvariable %} pk {% templatetag closevariable %}" type="checkbox" value="{% templatetag openvariable %} pk {% templatetag closevariable %}" data-name="{% templatetag openvariable %} name {% templatetag closevariable %}" data-color="{% templatetag openvariable %} color {% templatetag closevariable %}">
        </div>
        <div class="col-sm-11">
          <span class="icon-container" style="color:{% templatetag openvariable %} color {% templatetag closevariable %};"><span class="glyphicon glyphicon-tag"></span></span><label style="font-weight:normal;"for="category-{% templatetag openvariable %} pk {% templatetag closevariable %}" class="category-label">{% templatetag openvariable %} name {% templatetag closevariable %}</label>
        </div>
      </div>
  </template>
  <template id="new-category-template">
      <div class="row" data-pk="{% templatetag openvariable %} pk {% templatetag closevariable %}">
        <span class="icon-container" style="color:{% templatetag openvariable %} color {% templatetag closevariable %};"><span class="glyphicon glyphicon-tag"></span></span><label style="font-weight:normal;"for="category-{% templatetag openvariable %} pk {% templatetag closevariable %}" class="category-label">{% templatetag openvariable %} name {% templatetag closevariable %}</label>
      </div>
  </template>
{% endblock %}

{% block script %}<script src="{% static 'categories/js/category_merge.js' %}"></script>{% endblock %}